version: "3.1"
services:
  api:
    image: node:latest
    container_name: api
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: yarn && yarn start
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "6"
